services:
  devops:
    build: .
    image: devops:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - devops_data:/app/data
    networks:
      - devopsNet

networks:
  devopsNet:
    driver: bridge

volumes:
  devops_data:
    name: "devops-data"

#> docker compose up --build -d